name: pokedex
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  get_it: ^7.7.0
  mockito: ^5.4.4
  dio: ^5.6.0
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/lottie/

  fonts:
    - family: TTNorms_Bold
      fonts:
        - asset: assets/fonts/TTNormsPro_Bold.ttf

    - family: TTNorms_Medium
      fonts:
        - asset: assets/fonts/TTNormsPro_Medium.ttf

    - family: TTNorms_Regular
      fonts:
        - asset: assets/fonts/TTNormsPro_Regular.ttf

    - family: TTNormsPro_Light
      fonts:
        - asset: assets/fonts/TTNormsPro_Light.ttf